# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""


import grpc
from . import neumann_pb2 as neumann__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in neumann_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class QueryServiceStub:
    """Query service for executing Neumann queries."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
            "/neumann.v1.QueryService/Execute",
            request_serializer=neumann__pb2.QueryRequest.SerializeToString,
            response_deserializer=neumann__pb2.QueryResponse.FromString,
            _registered_method=True,
        )
        self.ExecuteStream = channel.unary_stream(
            "/neumann.v1.QueryService/ExecuteStream",
            request_serializer=neumann__pb2.QueryRequest.SerializeToString,
            response_deserializer=neumann__pb2.QueryResponseChunk.FromString,
            _registered_method=True,
        )
        self.ExecuteBatch = channel.unary_unary(
            "/neumann.v1.QueryService/ExecuteBatch",
            request_serializer=neumann__pb2.BatchQueryRequest.SerializeToString,
            response_deserializer=neumann__pb2.BatchQueryResponse.FromString,
            _registered_method=True,
        )
        self.ExecutePaginated = channel.unary_unary(
            "/neumann.v1.QueryService/ExecutePaginated",
            request_serializer=neumann__pb2.PaginatedQueryRequest.SerializeToString,
            response_deserializer=neumann__pb2.PaginatedQueryResponse.FromString,
            _registered_method=True,
        )
        self.CloseCursor = channel.unary_unary(
            "/neumann.v1.QueryService/CloseCursor",
            request_serializer=neumann__pb2.CloseCursorRequest.SerializeToString,
            response_deserializer=neumann__pb2.CloseCursorResponse.FromString,
            _registered_method=True,
        )


class QueryServiceServicer:
    """Query service for executing Neumann queries."""

    def Execute(self, request, context):
        """Execute a single query."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteStream(self, request, context):
        """Execute a query with streaming results (for large result sets)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteBatch(self, request, context):
        """Execute multiple queries in a batch."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecutePaginated(self, request, context):
        """Execute a paginated query with cursor-based navigation."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CloseCursor(self, request, context):
        """Close a cursor to free server resources."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Execute": grpc.unary_unary_rpc_method_handler(
            servicer.Execute,
            request_deserializer=neumann__pb2.QueryRequest.FromString,
            response_serializer=neumann__pb2.QueryResponse.SerializeToString,
        ),
        "ExecuteStream": grpc.unary_stream_rpc_method_handler(
            servicer.ExecuteStream,
            request_deserializer=neumann__pb2.QueryRequest.FromString,
            response_serializer=neumann__pb2.QueryResponseChunk.SerializeToString,
        ),
        "ExecuteBatch": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteBatch,
            request_deserializer=neumann__pb2.BatchQueryRequest.FromString,
            response_serializer=neumann__pb2.BatchQueryResponse.SerializeToString,
        ),
        "ExecutePaginated": grpc.unary_unary_rpc_method_handler(
            servicer.ExecutePaginated,
            request_deserializer=neumann__pb2.PaginatedQueryRequest.FromString,
            response_serializer=neumann__pb2.PaginatedQueryResponse.SerializeToString,
        ),
        "CloseCursor": grpc.unary_unary_rpc_method_handler(
            servicer.CloseCursor,
            request_deserializer=neumann__pb2.CloseCursorRequest.FromString,
            response_serializer=neumann__pb2.CloseCursorResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "neumann.v1.QueryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("neumann.v1.QueryService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class QueryService:
    """Query service for executing Neumann queries."""

    @staticmethod
    def Execute(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.v1.QueryService/Execute",
            neumann__pb2.QueryRequest.SerializeToString,
            neumann__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteStream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/neumann.v1.QueryService/ExecuteStream",
            neumann__pb2.QueryRequest.SerializeToString,
            neumann__pb2.QueryResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.v1.QueryService/ExecuteBatch",
            neumann__pb2.BatchQueryRequest.SerializeToString,
            neumann__pb2.BatchQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecutePaginated(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.v1.QueryService/ExecutePaginated",
            neumann__pb2.PaginatedQueryRequest.SerializeToString,
            neumann__pb2.PaginatedQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CloseCursor(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.v1.QueryService/CloseCursor",
            neumann__pb2.CloseCursorRequest.SerializeToString,
            neumann__pb2.CloseCursorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class BlobServiceStub:
    """Blob service for artifact storage."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
            "/neumann.v1.BlobService/Upload",
            request_serializer=neumann__pb2.BlobUploadRequest.SerializeToString,
            response_deserializer=neumann__pb2.BlobUploadResponse.FromString,
            _registered_method=True,
        )
        self.Download = channel.unary_stream(
            "/neumann.v1.BlobService/Download",
            request_serializer=neumann__pb2.BlobDownloadRequest.SerializeToString,
            response_deserializer=neumann__pb2.BlobDownloadChunk.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/neumann.v1.BlobService/Delete",
            request_serializer=neumann__pb2.BlobDeleteRequest.SerializeToString,
            response_deserializer=neumann__pb2.BlobDeleteResponse.FromString,
            _registered_method=True,
        )
        self.GetMetadata = channel.unary_unary(
            "/neumann.v1.BlobService/GetMetadata",
            request_serializer=neumann__pb2.BlobMetadataRequest.SerializeToString,
            response_deserializer=neumann__pb2.ArtifactInfo.FromString,
            _registered_method=True,
        )


class BlobServiceServicer:
    """Blob service for artifact storage."""

    def Upload(self, request_iterator, context):
        """Upload a blob with streaming chunks."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Download(self, request, context):
        """Download a blob with streaming chunks."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Delete a blob."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetMetadata(self, request, context):
        """Get artifact metadata."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BlobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Upload": grpc.stream_unary_rpc_method_handler(
            servicer.Upload,
            request_deserializer=neumann__pb2.BlobUploadRequest.FromString,
            response_serializer=neumann__pb2.BlobUploadResponse.SerializeToString,
        ),
        "Download": grpc.unary_stream_rpc_method_handler(
            servicer.Download,
            request_deserializer=neumann__pb2.BlobDownloadRequest.FromString,
            response_serializer=neumann__pb2.BlobDownloadChunk.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=neumann__pb2.BlobDeleteRequest.FromString,
            response_serializer=neumann__pb2.BlobDeleteResponse.SerializeToString,
        ),
        "GetMetadata": grpc.unary_unary_rpc_method_handler(
            servicer.GetMetadata,
            request_deserializer=neumann__pb2.BlobMetadataRequest.FromString,
            response_serializer=neumann__pb2.ArtifactInfo.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "neumann.v1.BlobService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("neumann.v1.BlobService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class BlobService:
    """Blob service for artifact storage."""

    @staticmethod
    def Upload(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/neumann.v1.BlobService/Upload",
            neumann__pb2.BlobUploadRequest.SerializeToString,
            neumann__pb2.BlobUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Download(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/neumann.v1.BlobService/Download",
            neumann__pb2.BlobDownloadRequest.SerializeToString,
            neumann__pb2.BlobDownloadChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.v1.BlobService/Delete",
            neumann__pb2.BlobDeleteRequest.SerializeToString,
            neumann__pb2.BlobDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetMetadata(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.v1.BlobService/GetMetadata",
            neumann__pb2.BlobMetadataRequest.SerializeToString,
            neumann__pb2.ArtifactInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class HealthStub:
    """Health check service."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
            "/neumann.v1.Health/Check",
            request_serializer=neumann__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=neumann__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class HealthServicer:
    """Health check service."""

    def Check(self, request, context):
        """Check server health."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HealthServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Check": grpc.unary_unary_rpc_method_handler(
            servicer.Check,
            request_deserializer=neumann__pb2.HealthCheckRequest.FromString,
            response_serializer=neumann__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("neumann.v1.Health", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("neumann.v1.Health", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Health:
    """Health check service."""

    @staticmethod
    def Check(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.v1.Health/Check",
            neumann__pb2.HealthCheckRequest.SerializeToString,
            neumann__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
