"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
SPDX-License-Identifier: MIT OR Apache-2.0"""

import builtins as _builtins
import typing as _typing
from collections import abc as _abc
from typing import TypeAlias as _TypeAlias

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Point(_message.Message):
    """A point with vector and optional payload."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PayloadEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    VECTOR_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Unique point identifier."""
    @_builtins.property
    def vector(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """Dense vector embedding."""

    @_builtins.property
    def payload(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """Optional payload as JSON-encoded values."""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        vector: _abc.Iterable[_builtins.float] | None = ...,
        payload: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "id", b"id", "payload", b"payload", "vector", b"vector"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Point: _TypeAlias = Point  # noqa: Y015

@_typing.final
class ScoredPoint(_message.Message):
    """A point with similarity score."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PayloadEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    VECTOR_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Unique point identifier."""
    score: _builtins.float
    """Similarity score."""
    @_builtins.property
    def payload(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """Optional payload."""

    @_builtins.property
    def vector(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """Optional vector (if requested)."""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        score: _builtins.float = ...,
        payload: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
        vector: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "id", b"id", "payload", b"payload", "score", b"score", "vector", b"vector"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScoredPoint: _TypeAlias = ScoredPoint  # noqa: Y015

@_typing.final
class UpsertPointsRequest(_message.Message):
    """Request to upsert points."""

    DESCRIPTOR: _descriptor.Descriptor

    COLLECTION_FIELD_NUMBER: _builtins.int
    POINTS_FIELD_NUMBER: _builtins.int
    collection: _builtins.str
    """Target collection name."""
    @_builtins.property
    def points(self) -> _containers.RepeatedCompositeFieldContainer[Global___Point]:
        """Points to upsert."""

    def __init__(
        self,
        *,
        collection: _builtins.str = ...,
        points: _abc.Iterable[Global___Point] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "collection", b"collection", "points", b"points"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpsertPointsRequest: _TypeAlias = UpsertPointsRequest  # noqa: Y015

@_typing.final
class UpsertPointsResponse(_message.Message):
    """Response from upsert operation."""

    DESCRIPTOR: _descriptor.Descriptor

    UPSERTED_FIELD_NUMBER: _builtins.int
    upserted: _builtins.int
    """Number of points upserted."""
    def __init__(
        self,
        *,
        upserted: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["upserted", b"upserted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpsertPointsResponse: _TypeAlias = UpsertPointsResponse  # noqa: Y015

@_typing.final
class GetPointsRequest(_message.Message):
    """Request to get points by IDs."""

    DESCRIPTOR: _descriptor.Descriptor

    COLLECTION_FIELD_NUMBER: _builtins.int
    IDS_FIELD_NUMBER: _builtins.int
    WITH_PAYLOAD_FIELD_NUMBER: _builtins.int
    WITH_VECTOR_FIELD_NUMBER: _builtins.int
    collection: _builtins.str
    """Target collection name."""
    with_payload: _builtins.bool
    """Include payload in response."""
    with_vector: _builtins.bool
    """Include vector in response."""
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Point IDs to retrieve."""

    def __init__(
        self,
        *,
        collection: _builtins.str = ...,
        ids: _abc.Iterable[_builtins.str] | None = ...,
        with_payload: _builtins.bool = ...,
        with_vector: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "collection",
        b"collection",
        "ids",
        b"ids",
        "with_payload",
        b"with_payload",
        "with_vector",
        b"with_vector",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPointsRequest: _TypeAlias = GetPointsRequest  # noqa: Y015

@_typing.final
class GetPointsResponse(_message.Message):
    """Response with retrieved points."""

    DESCRIPTOR: _descriptor.Descriptor

    POINTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def points(self) -> _containers.RepeatedCompositeFieldContainer[Global___Point]:
        """Retrieved points."""

    def __init__(
        self,
        *,
        points: _abc.Iterable[Global___Point] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["points", b"points"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPointsResponse: _TypeAlias = GetPointsResponse  # noqa: Y015

@_typing.final
class DeletePointsRequest(_message.Message):
    """Request to delete points."""

    DESCRIPTOR: _descriptor.Descriptor

    COLLECTION_FIELD_NUMBER: _builtins.int
    IDS_FIELD_NUMBER: _builtins.int
    collection: _builtins.str
    """Target collection name."""
    @_builtins.property
    def ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Point IDs to delete."""

    def __init__(
        self,
        *,
        collection: _builtins.str = ...,
        ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["collection", b"collection", "ids", b"ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeletePointsRequest: _TypeAlias = DeletePointsRequest  # noqa: Y015

@_typing.final
class DeletePointsResponse(_message.Message):
    """Response from delete operation."""

    DESCRIPTOR: _descriptor.Descriptor

    DELETED_FIELD_NUMBER: _builtins.int
    deleted: _builtins.int
    """Number of points deleted."""
    def __init__(
        self,
        *,
        deleted: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deleted", b"deleted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeletePointsResponse: _TypeAlias = DeletePointsResponse  # noqa: Y015

@_typing.final
class QueryPointsRequest(_message.Message):
    """Request to query similar points."""

    DESCRIPTOR: _descriptor.Descriptor

    COLLECTION_FIELD_NUMBER: _builtins.int
    VECTOR_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    SCORE_THRESHOLD_FIELD_NUMBER: _builtins.int
    WITH_PAYLOAD_FIELD_NUMBER: _builtins.int
    WITH_VECTOR_FIELD_NUMBER: _builtins.int
    collection: _builtins.str
    """Target collection name."""
    limit: _builtins.int
    """Maximum number of results."""
    offset: _builtins.int
    """Number of results to skip."""
    score_threshold: _builtins.float
    """Minimum similarity score threshold."""
    with_payload: _builtins.bool
    """Include payload in response."""
    with_vector: _builtins.bool
    """Include vector in response."""
    @_builtins.property
    def vector(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """Query vector."""

    def __init__(
        self,
        *,
        collection: _builtins.str = ...,
        vector: _abc.Iterable[_builtins.float] | None = ...,
        limit: _builtins.int = ...,
        offset: _builtins.int = ...,
        score_threshold: _builtins.float | None = ...,
        with_payload: _builtins.bool = ...,
        with_vector: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "_score_threshold", b"_score_threshold", "score_threshold", b"score_threshold"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "_score_threshold",
        b"_score_threshold",
        "collection",
        b"collection",
        "limit",
        b"limit",
        "offset",
        b"offset",
        "score_threshold",
        b"score_threshold",
        "vector",
        b"vector",
        "with_payload",
        b"with_payload",
        "with_vector",
        b"with_vector",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__score_threshold: _TypeAlias = _typing.Literal["score_threshold"]  # noqa: Y015
    _WhichOneofArgType__score_threshold: _TypeAlias = _typing.Literal[
        "_score_threshold", b"_score_threshold"
    ]  # noqa: Y015
    def WhichOneof(
        self, oneof_group: _WhichOneofArgType__score_threshold
    ) -> _WhichOneofReturnType__score_threshold | None: ...

Global___QueryPointsRequest: _TypeAlias = QueryPointsRequest  # noqa: Y015

@_typing.final
class QueryPointsResponse(_message.Message):
    """Response with similar points."""

    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScoredPoint]:
        """Similar points with scores."""

    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___ScoredPoint] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___QueryPointsResponse: _TypeAlias = QueryPointsResponse  # noqa: Y015

@_typing.final
class ScrollPointsRequest(_message.Message):
    """Request to scroll through points."""

    DESCRIPTOR: _descriptor.Descriptor

    COLLECTION_FIELD_NUMBER: _builtins.int
    OFFSET_ID_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    WITH_PAYLOAD_FIELD_NUMBER: _builtins.int
    WITH_VECTOR_FIELD_NUMBER: _builtins.int
    collection: _builtins.str
    """Target collection name."""
    offset_id: _builtins.str
    """Offset point ID for pagination."""
    limit: _builtins.int
    """Maximum number of points to return."""
    with_payload: _builtins.bool
    """Include payload in response."""
    with_vector: _builtins.bool
    """Include vector in response."""
    def __init__(
        self,
        *,
        collection: _builtins.str = ...,
        offset_id: _builtins.str | None = ...,
        limit: _builtins.int = ...,
        with_payload: _builtins.bool = ...,
        with_vector: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "_offset_id", b"_offset_id", "offset_id", b"offset_id"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "_offset_id",
        b"_offset_id",
        "collection",
        b"collection",
        "limit",
        b"limit",
        "offset_id",
        b"offset_id",
        "with_payload",
        b"with_payload",
        "with_vector",
        b"with_vector",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__offset_id: _TypeAlias = _typing.Literal["offset_id"]  # noqa: Y015
    _WhichOneofArgType__offset_id: _TypeAlias = _typing.Literal["_offset_id", b"_offset_id"]  # noqa: Y015
    def WhichOneof(
        self, oneof_group: _WhichOneofArgType__offset_id
    ) -> _WhichOneofReturnType__offset_id | None: ...

Global___ScrollPointsRequest: _TypeAlias = ScrollPointsRequest  # noqa: Y015

@_typing.final
class ScrollPointsResponse(_message.Message):
    """Response with scrolled points."""

    DESCRIPTOR: _descriptor.Descriptor

    POINTS_FIELD_NUMBER: _builtins.int
    NEXT_OFFSET_FIELD_NUMBER: _builtins.int
    next_offset: _builtins.str
    """Next offset ID for pagination."""
    @_builtins.property
    def points(self) -> _containers.RepeatedCompositeFieldContainer[Global___Point]:
        """Points in this page."""

    def __init__(
        self,
        *,
        points: _abc.Iterable[Global___Point] | None = ...,
        next_offset: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "_next_offset", b"_next_offset", "next_offset", b"next_offset"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "_next_offset", b"_next_offset", "next_offset", b"next_offset", "points", b"points"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__next_offset: _TypeAlias = _typing.Literal["next_offset"]  # noqa: Y015
    _WhichOneofArgType__next_offset: _TypeAlias = _typing.Literal["_next_offset", b"_next_offset"]  # noqa: Y015
    def WhichOneof(
        self, oneof_group: _WhichOneofArgType__next_offset
    ) -> _WhichOneofReturnType__next_offset | None: ...

Global___ScrollPointsResponse: _TypeAlias = ScrollPointsResponse  # noqa: Y015

@_typing.final
class CreateCollectionRequest(_message.Message):
    """Request to create a collection."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DIMENSION_FIELD_NUMBER: _builtins.int
    DISTANCE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Collection name."""
    dimension: _builtins.int
    """Vector dimension (required)."""
    distance: _builtins.str
    """Distance metric: "cosine", "euclidean", "dot"."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        dimension: _builtins.int = ...,
        distance: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "dimension", b"dimension", "distance", b"distance", "name", b"name"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateCollectionRequest: _TypeAlias = CreateCollectionRequest  # noqa: Y015

@_typing.final
class CreateCollectionResponse(_message.Message):
    """Response from create collection."""

    DESCRIPTOR: _descriptor.Descriptor

    CREATED_FIELD_NUMBER: _builtins.int
    created: _builtins.bool
    """Whether the collection was created."""
    def __init__(
        self,
        *,
        created: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created", b"created"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateCollectionResponse: _TypeAlias = CreateCollectionResponse  # noqa: Y015

@_typing.final
class GetCollectionRequest(_message.Message):
    """Request to get collection information."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Collection name."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetCollectionRequest: _TypeAlias = GetCollectionRequest  # noqa: Y015

@_typing.final
class GetCollectionResponse(_message.Message):
    """Response with collection information."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    POINTS_COUNT_FIELD_NUMBER: _builtins.int
    DIMENSION_FIELD_NUMBER: _builtins.int
    DISTANCE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Collection name."""
    points_count: _builtins.int
    """Number of points in collection."""
    dimension: _builtins.int
    """Vector dimension."""
    distance: _builtins.str
    """Distance metric."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        points_count: _builtins.int = ...,
        dimension: _builtins.int = ...,
        distance: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "dimension",
        b"dimension",
        "distance",
        b"distance",
        "name",
        b"name",
        "points_count",
        b"points_count",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetCollectionResponse: _TypeAlias = GetCollectionResponse  # noqa: Y015

@_typing.final
class DeleteCollectionRequest(_message.Message):
    """Request to delete a collection."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Collection name."""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteCollectionRequest: _TypeAlias = DeleteCollectionRequest  # noqa: Y015

@_typing.final
class DeleteCollectionResponse(_message.Message):
    """Response from delete collection."""

    DESCRIPTOR: _descriptor.Descriptor

    DELETED_FIELD_NUMBER: _builtins.int
    deleted: _builtins.bool
    """Whether the collection was deleted."""
    def __init__(
        self,
        *,
        deleted: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deleted", b"deleted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteCollectionResponse: _TypeAlias = DeleteCollectionResponse  # noqa: Y015

@_typing.final
class ListCollectionsRequest(_message.Message):
    """Request to list collections."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ListCollectionsRequest: _TypeAlias = ListCollectionsRequest  # noqa: Y015

@_typing.final
class ListCollectionsResponse(_message.Message):
    """Response with collection list."""

    DESCRIPTOR: _descriptor.Descriptor

    COLLECTIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def collections(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Collection names."""

    def __init__(
        self,
        *,
        collections: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["collections", b"collections"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListCollectionsResponse: _TypeAlias = ListCollectionsResponse  # noqa: Y015
