"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
SPDX-License-Identifier: MIT OR Apache-2.0"""

import abc as _abc_1
import sys
import typing as _typing
from collections import abc as _abc

import grpc as _grpc
import vector_pb2 as _vector_pb2
from grpc import aio as _aio

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...
class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class PointsServiceStub:
    """Points service for vector point operations."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> PointsServiceAsyncStub: ...  # type: ignore[overload-cannot-match]
    Upsert: _grpc.UnaryUnaryMultiCallable[
        _vector_pb2.UpsertPointsRequest, _vector_pb2.UpsertPointsResponse
    ]
    """Upsert points into a collection."""
    Get: _grpc.UnaryUnaryMultiCallable[_vector_pb2.GetPointsRequest, _vector_pb2.GetPointsResponse]
    """Get points by IDs."""
    Delete: _grpc.UnaryUnaryMultiCallable[
        _vector_pb2.DeletePointsRequest, _vector_pb2.DeletePointsResponse
    ]
    """Delete points by IDs."""
    Query: _grpc.UnaryUnaryMultiCallable[
        _vector_pb2.QueryPointsRequest, _vector_pb2.QueryPointsResponse
    ]
    """Query similar points."""
    Scroll: _grpc.UnaryUnaryMultiCallable[
        _vector_pb2.ScrollPointsRequest, _vector_pb2.ScrollPointsResponse
    ]
    """Scroll through points in a collection."""

@_typing.type_check_only
class PointsServiceAsyncStub(PointsServiceStub):
    """Points service for vector point operations."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Upsert: _aio.UnaryUnaryMultiCallable[
        _vector_pb2.UpsertPointsRequest, _vector_pb2.UpsertPointsResponse
    ]
    """Upsert points into a collection."""
    Get: _aio.UnaryUnaryMultiCallable[_vector_pb2.GetPointsRequest, _vector_pb2.GetPointsResponse]
    """Get points by IDs."""
    Delete: _aio.UnaryUnaryMultiCallable[
        _vector_pb2.DeletePointsRequest, _vector_pb2.DeletePointsResponse
    ]
    """Delete points by IDs."""
    Query: _aio.UnaryUnaryMultiCallable[
        _vector_pb2.QueryPointsRequest, _vector_pb2.QueryPointsResponse
    ]
    """Query similar points."""
    Scroll: _aio.UnaryUnaryMultiCallable[
        _vector_pb2.ScrollPointsRequest, _vector_pb2.ScrollPointsResponse
    ]
    """Scroll through points in a collection."""

class PointsServiceServicer(metaclass=_abc_1.ABCMeta):
    """Points service for vector point operations."""

    @_abc_1.abstractmethod
    def Upsert(
        self,
        request: _vector_pb2.UpsertPointsRequest,
        context: _ServicerContext,
    ) -> _vector_pb2.UpsertPointsResponse | _abc.Awaitable[_vector_pb2.UpsertPointsResponse]:
        """Upsert points into a collection."""

    @_abc_1.abstractmethod
    def Get(
        self,
        request: _vector_pb2.GetPointsRequest,
        context: _ServicerContext,
    ) -> _vector_pb2.GetPointsResponse | _abc.Awaitable[_vector_pb2.GetPointsResponse]:
        """Get points by IDs."""

    @_abc_1.abstractmethod
    def Delete(
        self,
        request: _vector_pb2.DeletePointsRequest,
        context: _ServicerContext,
    ) -> _vector_pb2.DeletePointsResponse | _abc.Awaitable[_vector_pb2.DeletePointsResponse]:
        """Delete points by IDs."""

    @_abc_1.abstractmethod
    def Query(
        self,
        request: _vector_pb2.QueryPointsRequest,
        context: _ServicerContext,
    ) -> _vector_pb2.QueryPointsResponse | _abc.Awaitable[_vector_pb2.QueryPointsResponse]:
        """Query similar points."""

    @_abc_1.abstractmethod
    def Scroll(
        self,
        request: _vector_pb2.ScrollPointsRequest,
        context: _ServicerContext,
    ) -> _vector_pb2.ScrollPointsResponse | _abc.Awaitable[_vector_pb2.ScrollPointsResponse]:
        """Scroll through points in a collection."""

def add_PointsServiceServicer_to_server(
    servicer: PointsServiceServicer, server: _grpc.Server | _aio.Server
) -> None: ...

class CollectionsServiceStub:
    """Collections service for collection management."""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> CollectionsServiceAsyncStub: ...  # type: ignore[overload-cannot-match]
    Create: _grpc.UnaryUnaryMultiCallable[
        _vector_pb2.CreateCollectionRequest, _vector_pb2.CreateCollectionResponse
    ]
    """Create a new collection."""
    Get: _grpc.UnaryUnaryMultiCallable[
        _vector_pb2.GetCollectionRequest, _vector_pb2.GetCollectionResponse
    ]
    """Get collection information."""
    Delete: _grpc.UnaryUnaryMultiCallable[
        _vector_pb2.DeleteCollectionRequest, _vector_pb2.DeleteCollectionResponse
    ]
    """Delete a collection."""
    List: _grpc.UnaryUnaryMultiCallable[
        _vector_pb2.ListCollectionsRequest, _vector_pb2.ListCollectionsResponse
    ]
    """List all collections."""

@_typing.type_check_only
class CollectionsServiceAsyncStub(CollectionsServiceStub):
    """Collections service for collection management."""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Create: _aio.UnaryUnaryMultiCallable[
        _vector_pb2.CreateCollectionRequest, _vector_pb2.CreateCollectionResponse
    ]
    """Create a new collection."""
    Get: _aio.UnaryUnaryMultiCallable[
        _vector_pb2.GetCollectionRequest, _vector_pb2.GetCollectionResponse
    ]
    """Get collection information."""
    Delete: _aio.UnaryUnaryMultiCallable[
        _vector_pb2.DeleteCollectionRequest, _vector_pb2.DeleteCollectionResponse
    ]
    """Delete a collection."""
    List: _aio.UnaryUnaryMultiCallable[
        _vector_pb2.ListCollectionsRequest, _vector_pb2.ListCollectionsResponse
    ]
    """List all collections."""

class CollectionsServiceServicer(metaclass=_abc_1.ABCMeta):
    """Collections service for collection management."""

    @_abc_1.abstractmethod
    def Create(
        self,
        request: _vector_pb2.CreateCollectionRequest,
        context: _ServicerContext,
    ) -> _vector_pb2.CreateCollectionResponse | _abc.Awaitable[_vector_pb2.CreateCollectionResponse]:
        """Create a new collection."""

    @_abc_1.abstractmethod
    def Get(
        self,
        request: _vector_pb2.GetCollectionRequest,
        context: _ServicerContext,
    ) -> _vector_pb2.GetCollectionResponse | _abc.Awaitable[_vector_pb2.GetCollectionResponse]:
        """Get collection information."""

    @_abc_1.abstractmethod
    def Delete(
        self,
        request: _vector_pb2.DeleteCollectionRequest,
        context: _ServicerContext,
    ) -> _vector_pb2.DeleteCollectionResponse | _abc.Awaitable[_vector_pb2.DeleteCollectionResponse]:
        """Delete a collection."""

    @_abc_1.abstractmethod
    def List(
        self,
        request: _vector_pb2.ListCollectionsRequest,
        context: _ServicerContext,
    ) -> _vector_pb2.ListCollectionsResponse | _abc.Awaitable[_vector_pb2.ListCollectionsResponse]:
        """List all collections."""

def add_CollectionsServiceServicer_to_server(
    servicer: CollectionsServiceServicer, server: _grpc.Server | _aio.Server
) -> None: ...
