# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import vector_pb2 as vector__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in vector_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PointsServiceStub:
    """Points service for vector point operations."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upsert = channel.unary_unary(
            "/neumann.vector.v1.PointsService/Upsert",
            request_serializer=vector__pb2.UpsertPointsRequest.SerializeToString,
            response_deserializer=vector__pb2.UpsertPointsResponse.FromString,
            _registered_method=True,
        )
        self.Get = channel.unary_unary(
            "/neumann.vector.v1.PointsService/Get",
            request_serializer=vector__pb2.GetPointsRequest.SerializeToString,
            response_deserializer=vector__pb2.GetPointsResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/neumann.vector.v1.PointsService/Delete",
            request_serializer=vector__pb2.DeletePointsRequest.SerializeToString,
            response_deserializer=vector__pb2.DeletePointsResponse.FromString,
            _registered_method=True,
        )
        self.Query = channel.unary_unary(
            "/neumann.vector.v1.PointsService/Query",
            request_serializer=vector__pb2.QueryPointsRequest.SerializeToString,
            response_deserializer=vector__pb2.QueryPointsResponse.FromString,
            _registered_method=True,
        )
        self.Scroll = channel.unary_unary(
            "/neumann.vector.v1.PointsService/Scroll",
            request_serializer=vector__pb2.ScrollPointsRequest.SerializeToString,
            response_deserializer=vector__pb2.ScrollPointsResponse.FromString,
            _registered_method=True,
        )


class PointsServiceServicer:
    """Points service for vector point operations."""

    def Upsert(self, _request, _context):
        """Upsert points into a collection."""
        _context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        _context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, _request, _context):
        """Get points by IDs."""
        _context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        _context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, _request, _context):
        """Delete points by IDs."""
        _context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        _context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Query(self, _request, _context):
        """Query similar points."""
        _context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        _context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Scroll(self, _request, _context):
        """Scroll through points in a collection."""
        _context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        _context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PointsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Upsert": grpc.unary_unary_rpc_method_handler(
            servicer.Upsert,
            request_deserializer=vector__pb2.UpsertPointsRequest.FromString,
            response_serializer=vector__pb2.UpsertPointsResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=vector__pb2.GetPointsRequest.FromString,
            response_serializer=vector__pb2.GetPointsResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=vector__pb2.DeletePointsRequest.FromString,
            response_serializer=vector__pb2.DeletePointsResponse.SerializeToString,
        ),
        "Query": grpc.unary_unary_rpc_method_handler(
            servicer.Query,
            request_deserializer=vector__pb2.QueryPointsRequest.FromString,
            response_serializer=vector__pb2.QueryPointsResponse.SerializeToString,
        ),
        "Scroll": grpc.unary_unary_rpc_method_handler(
            servicer.Scroll,
            request_deserializer=vector__pb2.ScrollPointsRequest.FromString,
            response_serializer=vector__pb2.ScrollPointsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "neumann.vector.v1.PointsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("neumann.vector.v1.PointsService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PointsService:
    """Points service for vector point operations."""

    @staticmethod
    def Upsert(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.vector.v1.PointsService/Upsert",
            vector__pb2.UpsertPointsRequest.SerializeToString,
            vector__pb2.UpsertPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.vector.v1.PointsService/Get",
            vector__pb2.GetPointsRequest.SerializeToString,
            vector__pb2.GetPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.vector.v1.PointsService/Delete",
            vector__pb2.DeletePointsRequest.SerializeToString,
            vector__pb2.DeletePointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Query(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.vector.v1.PointsService/Query",
            vector__pb2.QueryPointsRequest.SerializeToString,
            vector__pb2.QueryPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Scroll(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.vector.v1.PointsService/Scroll",
            vector__pb2.ScrollPointsRequest.SerializeToString,
            vector__pb2.ScrollPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class CollectionsServiceStub:
    """Collections service for collection management."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/neumann.vector.v1.CollectionsService/Create",
            request_serializer=vector__pb2.CreateCollectionRequest.SerializeToString,
            response_deserializer=vector__pb2.CreateCollectionResponse.FromString,
            _registered_method=True,
        )
        self.Get = channel.unary_unary(
            "/neumann.vector.v1.CollectionsService/Get",
            request_serializer=vector__pb2.GetCollectionRequest.SerializeToString,
            response_deserializer=vector__pb2.GetCollectionResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/neumann.vector.v1.CollectionsService/Delete",
            request_serializer=vector__pb2.DeleteCollectionRequest.SerializeToString,
            response_deserializer=vector__pb2.DeleteCollectionResponse.FromString,
            _registered_method=True,
        )
        self.List = channel.unary_unary(
            "/neumann.vector.v1.CollectionsService/List",
            request_serializer=vector__pb2.ListCollectionsRequest.SerializeToString,
            response_deserializer=vector__pb2.ListCollectionsResponse.FromString,
            _registered_method=True,
        )


class CollectionsServiceServicer:
    """Collections service for collection management."""

    def Create(self, _request, _context):
        """Create a new collection."""
        _context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        _context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, _request, _context):
        """Get collection information."""
        _context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        _context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, _request, _context):
        """Delete a collection."""
        _context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        _context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, _request, _context):
        """List all collections."""
        _context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        _context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CollectionsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=vector__pb2.CreateCollectionRequest.FromString,
            response_serializer=vector__pb2.CreateCollectionResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=vector__pb2.GetCollectionRequest.FromString,
            response_serializer=vector__pb2.GetCollectionResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=vector__pb2.DeleteCollectionRequest.FromString,
            response_serializer=vector__pb2.DeleteCollectionResponse.SerializeToString,
        ),
        "List": grpc.unary_unary_rpc_method_handler(
            servicer.List,
            request_deserializer=vector__pb2.ListCollectionsRequest.FromString,
            response_serializer=vector__pb2.ListCollectionsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "neumann.vector.v1.CollectionsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "neumann.vector.v1.CollectionsService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class CollectionsService:
    """Collections service for collection management."""

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.vector.v1.CollectionsService/Create",
            vector__pb2.CreateCollectionRequest.SerializeToString,
            vector__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.vector.v1.CollectionsService/Get",
            vector__pb2.GetCollectionRequest.SerializeToString,
            vector__pb2.GetCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.vector.v1.CollectionsService/Delete",
            vector__pb2.DeleteCollectionRequest.SerializeToString,
            vector__pb2.DeleteCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neumann.vector.v1.CollectionsService/List",
            vector__pb2.ListCollectionsRequest.SerializeToString,
            vector__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
